# Generated by Django 3.2.13 on 2024-01-29 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ranked', models.BooleanField()),
                ('addition_per_minute', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('correct_answer', models.IntegerField()),
                ('modified_answer', models.IntegerField()),
                ('incorrect_answer', models.IntegerField()),
                ('test_type', models.CharField(choices=[('pauli', 'Pauli'), ('kraepelin', 'Kraepelin')], max_length=16)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
